# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/javi/MasterInformatica/2Q/AG/SolarSystem

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/javi/MasterInformatica/2Q/AG/SolarSystem

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip

.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local

.PHONY : install/local/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/javi/MasterInformatica/2Q/AG/SolarSystem/CMakeFiles /home/javi/MasterInformatica/2Q/AG/SolarSystem/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/javi/MasterInformatica/2Q/AG/SolarSystem/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Glitter

# Build rule for target.
Glitter: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Glitter
.PHONY : Glitter

# fast build rule for target.
Glitter/fast:
	$(MAKE) -f CMakeFiles/Glitter.dir/build.make CMakeFiles/Glitter.dir/build
.PHONY : Glitter/fast

#=============================================================================
# Target rules for targets named uninstall

# Build rule for target.
uninstall: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 uninstall
.PHONY : uninstall

# fast build rule for target.
uninstall/fast:
	$(MAKE) -f Glitter/Vendor/glfw/CMakeFiles/uninstall.dir/build.make Glitter/Vendor/glfw/CMakeFiles/uninstall.dir/build
.PHONY : uninstall/fast

#=============================================================================
# Target rules for targets named glfw

# Build rule for target.
glfw: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 glfw
.PHONY : glfw

# fast build rule for target.
glfw/fast:
	$(MAKE) -f Glitter/Vendor/glfw/src/CMakeFiles/glfw.dir/build.make Glitter/Vendor/glfw/src/CMakeFiles/glfw.dir/build
.PHONY : glfw/fast

Glitter/Sources/ShaderProgram.o: Glitter/Sources/ShaderProgram.cpp.o

.PHONY : Glitter/Sources/ShaderProgram.o

# target to build an object file
Glitter/Sources/ShaderProgram.cpp.o:
	$(MAKE) -f CMakeFiles/Glitter.dir/build.make CMakeFiles/Glitter.dir/Glitter/Sources/ShaderProgram.cpp.o
.PHONY : Glitter/Sources/ShaderProgram.cpp.o

Glitter/Sources/ShaderProgram.i: Glitter/Sources/ShaderProgram.cpp.i

.PHONY : Glitter/Sources/ShaderProgram.i

# target to preprocess a source file
Glitter/Sources/ShaderProgram.cpp.i:
	$(MAKE) -f CMakeFiles/Glitter.dir/build.make CMakeFiles/Glitter.dir/Glitter/Sources/ShaderProgram.cpp.i
.PHONY : Glitter/Sources/ShaderProgram.cpp.i

Glitter/Sources/ShaderProgram.s: Glitter/Sources/ShaderProgram.cpp.s

.PHONY : Glitter/Sources/ShaderProgram.s

# target to generate assembly for a file
Glitter/Sources/ShaderProgram.cpp.s:
	$(MAKE) -f CMakeFiles/Glitter.dir/build.make CMakeFiles/Glitter.dir/Glitter/Sources/ShaderProgram.cpp.s
.PHONY : Glitter/Sources/ShaderProgram.cpp.s

Glitter/Sources/Sphere.o: Glitter/Sources/Sphere.cpp.o

.PHONY : Glitter/Sources/Sphere.o

# target to build an object file
Glitter/Sources/Sphere.cpp.o:
	$(MAKE) -f CMakeFiles/Glitter.dir/build.make CMakeFiles/Glitter.dir/Glitter/Sources/Sphere.cpp.o
.PHONY : Glitter/Sources/Sphere.cpp.o

Glitter/Sources/Sphere.i: Glitter/Sources/Sphere.cpp.i

.PHONY : Glitter/Sources/Sphere.i

# target to preprocess a source file
Glitter/Sources/Sphere.cpp.i:
	$(MAKE) -f CMakeFiles/Glitter.dir/build.make CMakeFiles/Glitter.dir/Glitter/Sources/Sphere.cpp.i
.PHONY : Glitter/Sources/Sphere.cpp.i

Glitter/Sources/Sphere.s: Glitter/Sources/Sphere.cpp.s

.PHONY : Glitter/Sources/Sphere.s

# target to generate assembly for a file
Glitter/Sources/Sphere.cpp.s:
	$(MAKE) -f CMakeFiles/Glitter.dir/build.make CMakeFiles/Glitter.dir/Glitter/Sources/Sphere.cpp.s
.PHONY : Glitter/Sources/Sphere.cpp.s

Glitter/Sources/main.o: Glitter/Sources/main.cpp.o

.PHONY : Glitter/Sources/main.o

# target to build an object file
Glitter/Sources/main.cpp.o:
	$(MAKE) -f CMakeFiles/Glitter.dir/build.make CMakeFiles/Glitter.dir/Glitter/Sources/main.cpp.o
.PHONY : Glitter/Sources/main.cpp.o

Glitter/Sources/main.i: Glitter/Sources/main.cpp.i

.PHONY : Glitter/Sources/main.i

# target to preprocess a source file
Glitter/Sources/main.cpp.i:
	$(MAKE) -f CMakeFiles/Glitter.dir/build.make CMakeFiles/Glitter.dir/Glitter/Sources/main.cpp.i
.PHONY : Glitter/Sources/main.cpp.i

Glitter/Sources/main.s: Glitter/Sources/main.cpp.s

.PHONY : Glitter/Sources/main.s

# target to generate assembly for a file
Glitter/Sources/main.cpp.s:
	$(MAKE) -f CMakeFiles/Glitter.dir/build.make CMakeFiles/Glitter.dir/Glitter/Sources/main.cpp.s
.PHONY : Glitter/Sources/main.cpp.s

Glitter/Vendor/glad/src/glad.o: Glitter/Vendor/glad/src/glad.c.o

.PHONY : Glitter/Vendor/glad/src/glad.o

# target to build an object file
Glitter/Vendor/glad/src/glad.c.o:
	$(MAKE) -f CMakeFiles/Glitter.dir/build.make CMakeFiles/Glitter.dir/Glitter/Vendor/glad/src/glad.c.o
.PHONY : Glitter/Vendor/glad/src/glad.c.o

Glitter/Vendor/glad/src/glad.i: Glitter/Vendor/glad/src/glad.c.i

.PHONY : Glitter/Vendor/glad/src/glad.i

# target to preprocess a source file
Glitter/Vendor/glad/src/glad.c.i:
	$(MAKE) -f CMakeFiles/Glitter.dir/build.make CMakeFiles/Glitter.dir/Glitter/Vendor/glad/src/glad.c.i
.PHONY : Glitter/Vendor/glad/src/glad.c.i

Glitter/Vendor/glad/src/glad.s: Glitter/Vendor/glad/src/glad.c.s

.PHONY : Glitter/Vendor/glad/src/glad.s

# target to generate assembly for a file
Glitter/Vendor/glad/src/glad.c.s:
	$(MAKE) -f CMakeFiles/Glitter.dir/build.make CMakeFiles/Glitter.dir/Glitter/Vendor/glad/src/glad.c.s
.PHONY : Glitter/Vendor/glad/src/glad.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... Glitter"
	@echo "... install/strip"
	@echo "... install/local"
	@echo "... edit_cache"
	@echo "... uninstall"
	@echo "... glfw"
	@echo "... Glitter/Sources/ShaderProgram.o"
	@echo "... Glitter/Sources/ShaderProgram.i"
	@echo "... Glitter/Sources/ShaderProgram.s"
	@echo "... Glitter/Sources/Sphere.o"
	@echo "... Glitter/Sources/Sphere.i"
	@echo "... Glitter/Sources/Sphere.s"
	@echo "... Glitter/Sources/main.o"
	@echo "... Glitter/Sources/main.i"
	@echo "... Glitter/Sources/main.s"
	@echo "... Glitter/Vendor/glad/src/glad.o"
	@echo "... Glitter/Vendor/glad/src/glad.i"
	@echo "... Glitter/Vendor/glad/src/glad.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

